### ISSUE TITLE
Discord group invite

### ISSUE THREAD

**Issue by pelleknaap** [zero-to-mastery/Coding_Challenge-5#1]
Hello,

I'm wondering if there is any way I can join the #coding-challenge Discord group. 
I don't see an invite link in the .readme file so could you maybe add it to the .readme file or send it here? 
Would be really nice.

Sincerely,
Pelle

**Comment by aneagoie** [comment]
The Discord group invite link is in the lecture 3 of the course :)

**Comment by online-code-bite-md-tanvir-mahtab** [comment]
hello sir i want to join in your discord server please let me in i ma learning data science on Udemy where your the instructor

**Comment by nneverson** [comment]
Hello the discord invite link is invalid
